package: media_manager
version: '2.14.0'
author: 'Markus Staab, Jan Kristinus'
supportpage: https://github.com/redaxo/redaxo

page:
    title: 'Media Manager'
    perm: admin
    pjax: true
    icon: rex-icon rex-icon-media
    subpages:
        types: { title: 'translate:media_manager_subpage_types' }
        settings: { title: 'translate:media_manager_subpage_config' }
        overview: { title: 'translate:media_manager_subpage_desc', subPath: README.md }
        clear_cache: { title: 'translate:media_manager_subpage_clear_cache', itemClass: 'pull-right', linkClass: 'btn btn-delete', href: { page: media_manager/types, func: clear_cache } }

requires:
    php:
        version: '>=8.1'
        extensions: [gd]
    redaxo: ^5.15.0

default_config:
    jpg_quality: 80
    png_compression: 5
    webp_quality: 85
    avif_quality: 60
    avif_speed: 6
    interlace: [jpg]
