<?php

return [
    'vendor/bootstrap/assets/javascripts/bootstrap.js' => 'js/bootstrap.js',
    'vendor/bootstrap/assets/fonts/bootstrap/glyphicons-halflings-regular.eot' => 'fonts/bootstrap/glyphicons-halflings-regular.eot',
    'vendor/bootstrap/assets/fonts/bootstrap/glyphicons-halflings-regular.svg' => 'fonts/bootstrap/glyphicons-halflings-regular.svg',
    'vendor/bootstrap/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf' => 'fonts/bootstrap/glyphicons-halflings-regular.ttf',
    'vendor/bootstrap/assets/fonts/bootstrap/glyphicons-halflings-regular.woff' => 'fonts/bootstrap/glyphicons-halflings-regular.woff',
    'vendor/bootstrap/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2' => 'fonts/bootstrap/glyphicons-halflings-regular.woff2',
    'vendor/bootstrap-select/dist/css/bootstrap-select.min.css' => 'css/bootstrap-select.min.css',
    'vendor/bootstrap-select/dist/js/bootstrap-select.min.js' => 'js/bootstrap-select.min.js',
    'vendor/bootstrap-select/dist/js/bootstrap-select.min.js.map' => 'js/bootstrap-select.min.js.map',
    'vendor/bootstrap-select/dist/js/i18n/defaults-de_DE.min.js' => 'js/bootstrap-select-defaults-de_DE.min.js',
    'vendor/bootstrap-select/dist/js/i18n/defaults-en_US.min.js' => 'js/bootstrap-select-defaults-en_US.min.js',
    'vendor/bootstrap-select/dist/js/i18n/defaults-es_ES.min.js' => 'js/bootstrap-select-defaults-es_ES.min.js',
    'vendor/bootstrap-select/dist/js/i18n/defaults-it_IT.min.js' => 'js/bootstrap-select-defaults-it_IT.min.js',
    'vendor/bootstrap-select/dist/js/i18n/defaults-nl_NL.min.js' => 'js/bootstrap-select-defaults-nl_NL.min.js',
    'vendor/bootstrap-select/dist/js/i18n/defaults-pt_BR.min.js' => 'js/bootstrap-select-defaults-pt_BR.min.js',
    'vendor/bootstrap-select/dist/js/i18n/defaults-sv_SE.min.js' => 'js/bootstrap-select-defaults-sv_SE.min.js',
    'vendor/font-awesome/webfonts/fa-brands-400.ttf' => 'webfonts/fa-brands-400.ttf',
    'vendor/font-awesome/webfonts/fa-brands-400.woff2' => 'webfonts/fa-brands-400.woff2',
    'vendor/font-awesome/webfonts/fa-regular-400.ttf' => 'webfonts/fa-regular-400.ttf',
    'vendor/font-awesome/webfonts/fa-regular-400.woff2' => 'webfonts/fa-regular-400.woff2',
    'vendor/font-awesome/webfonts/fa-solid-900.ttf' => 'webfonts/fa-solid-900.ttf',
    'vendor/font-awesome/webfonts/fa-solid-900.woff2' => 'webfonts/fa-solid-900.woff2',
    'vendor/font-awesome/webfonts/fa-v4compatibility.ttf' => 'webfonts/fa-v4compatibility.ttf',
    'vendor/font-awesome/webfonts/fa-v4compatibility.woff2' => 'webfonts/fa-v4compatibility.woff2',
];
