package: backup
version: '2.8.2'
author: 'Jan Kristinus, Markus Staab'
supportpage: https://github.com/redaxo/redaxo

page:
    title: 'translate:backup_title'
    perm: backup[export]
    pjax: true
    icon: rex-icon rex-icon-backup
    subpages:
        export: { title: 'translate:backup_export' }
        import:
            title: 'translate:backup_import'
            perm: 'admin[]'
            subpages:
                upload: { title: 'translate:backup_upload' }
                server: { title: 'translate:backup_load_from_server' }

requires:
    php:
        version: '>=7.3'
        extensions: [ctype]
    redaxo: ^5.9.0
