version: '5.0 a1'
author: 'Jan Kristinus, Markus Staab'
supportpage: www.redaxo.org/de/forum/

navigation:
  title: 'translate:im_export_importexport'
  perm: import_export[export]
  subpages:
    export: {title: 'translate:im_export_export'}
    import: {title: 'translate:im_export_import', perm: 'import_export[import]'}
