package: import_export
version: '5.0-alpha7'
author: 'Jan Kristinus, Markus Staab'
supportpage: www.redaxo.org/de/forum/

page:
    title: 'translate:im_export_importexport'
    perm: import_export[export]
    pjax: true
    subpages:
        export: { title: 'translate:im_export_export' }
        import: { title: 'translate:im_export_import', perm: 'import_export[import]' }
