CREATE TABLE IF NOT EXISTS `%TABLE_PREFIX%article` (
    `pid` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `id` int(10) unsigned NOT NULL,
    `parent_id` int(10) unsigned NOT NULL,
    `name` varchar(255) NOT NULL,
    `catname` varchar(255) NOT NULL,
    `catpriority` int(10) unsigned NOT NULL,
    `startarticle` tinyint(1) NOT NULL,
    `priority` int(10) unsigned NOT NULL,
    `path` varchar(255) NOT NULL,
    `status` tinyint(1) NOT NULL,
    `createdate` datetime NOT NULL,
    `updatedate` datetime NOT NULL,
    `template_id` int(10) unsigned NOT NULL,
    `clang_id` int(10) unsigned NOT NULL,
    `createuser` varchar(255) NOT NULL,
    `updateuser` varchar(255) NOT NULL,
    `revision` int(10) unsigned NOT NULL,
    PRIMARY KEY (`pid`),
    UNIQUE KEY `find_articles` (`id`,`clang_id`),
    KEY `id` (`id`),
    KEY `clang_id` (`clang_id`),
    KEY `parent_id` (`parent_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;
