CREATE TABLE IF NOT EXISTS `%TABLE_PREFIX%article` (
    `pid` int(11) NOT NULL AUTO_INCREMENT,
    `id` int(11) NOT NULL,
    `parent_id` int(11) NOT NULL,
    `name` varchar(255) NOT NULL,
    `catname` varchar(255) NOT NULL,
    `catprior` int(11) NOT NULL,
    `startarticle` tinyint(1) NOT NULL,
    `prior` int(11) NOT NULL,
    `path` varchar(255) NOT NULL,
    `status` tinyint(1) NOT NULL,
    `createdate` int(11) NOT NULL,
    `updatedate` int(11) NOT NULL,
    `template_id` int(11) NOT NULL,
    `clang` int(11) NOT NULL,
    `createuser` varchar(255) NOT NULL,
    `updateuser` varchar(255) NOT NULL,
    `revision` int(11) NOT NULL,
    PRIMARY KEY (`pid`),
    UNIQUE KEY `find_articles` (`id`,`clang`),
    KEY `id` (`id`),
    KEY `clang` (`clang`),
    KEY `parent_id` (`parent_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 ;
