package: structure
version: '2.15.0'
author: Markus Staab
supportpage: https://github.com/redaxo/redaxo

rows_per_page:  50

page:
    title: translate:structure
    perm: structure/hasStructurePerm
    block: system
    prio: 10
    pjax: true
    icon: rex-icon rex-icon-open-category

pages:
    linkmap:
        title: translate:linkmap
        main: true
        block: system
        popup: true
        hidden: true
        perm: structure/hasStructurePerm
        pjax: true
    content/history:
        title: ' '
        icon: 'fa fa-history'
        href: '#'
        itemAttr:
            left: true
        linkAttr:
            data-history-layer: open
        perm: history[article_rollback]
    system/history:
        title: translate:structure_history

system_plugins: [content]

requires:
    php: '>=8.1'
    redaxo: ^5.15.0

default_config:
    start_article_id: 1
    notfound_article_id: 1

extensions:
    history:
        available: true
    version:
        available: true
