package: structure
version: '3.0.0-dev'
author: Markus Staab
supportpage: https://github.com/redaxo/redaxo

rows_per_page:  50

page:
    title: translate:structure
    perm: structure/hasStructurePerm
    block: system
    prio: 10
    pjax: true
    icon: rex-icon rex-icon-open-category

pages:
    linkmap:
        title: translate:linkmap
        main: true
        block: system
        popup: true
        hidden: true
        perm: structure/hasStructurePerm
        pjax: true

system_plugins: [content]

requires:
    php: '>=8.1'
    redaxo: ^6.0.0-dev

default_config:
    start_article_id: 1
    notfound_article_id: 1
