package: be_style
version: '2.12.0'
author: 'Jan Kristinus, Markus Staab, Thomas Blum'
supportpage: https://github.com/redaxo/redaxo

load: early
system_plugins: [redaxo]
compile: 0

console_commands:
    be_style:compile: rex_be_style_command_compile
    styles:compile: rex_be_style_command_compile

requires:
    php: '>=7.3'
    redaxo: ^5.12.0
