package: be_style
version: '2.10.1'
author: 'Jan Kristinus, Markus Staab, Thomas Blum'
supportpage: www.redaxo.org/de/forum/

load: early
system_plugins: [redaxo]
compile: 0

console_commands:
    be_style:compile: rex_be_style_command_compile
    styles:compile: rex_be_style_command_compile

requires:
    php: '>=7.1'
    redaxo: ^5.10.0
