package: be_style
version: '4.0.0-dev'
author: 'Jan Kristinus, Markus Staab, Thomas Blum'
supportpage: https://github.com/redaxo/redaxo

load: early
system_plugins: [redaxo]
compile: 0

console_commands:
    be_style:compile: rex_be_style_command_compile
    styles:compile: rex_be_style_command_compile

requires:
    php: '>=8.1'
    redaxo: ^6.0.0-dev
