package: install
version: '2.4.0'
author: Gregor Harlan
supportpage: www.redaxo.org/de/forum

page:
    title: 'translate:title'
    perm: admin[]
    block: system
    prio: 80
    pjax: true
    icon: rex-icon rex-icon-install
    subpages:
        packages:
            title: 'translate:subpage_packages'
            subpages:
                update: { title: 'translate:subpage_update' }
                add: { title: 'translate:subpage_add' }
                upload: { title: 'translate:subpage_upload' }
        settings: { title: 'translate:subpage_settings' }

requires:
    php:
        extensions: [zlib]
    redaxo: ^5.5.0
