install:
  version: '1.0'
  author: Jan Kristinus
  supportpage: www.redaxo.org/de/forum

  name: 'translate:install_name'
  perm: admin[]
  pages:
    - ['', 'translate:install_name']

  requires:
    redaxo:
      min-version: '5.0'