<?php

use Symfony\Component\Console\Command\ListCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

class rex_command_list extends ListCommand {

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub

        if (rex::isSetup()) {
            $io = new SymfonyStyle($input, $output);

            $io->text('These commands are available during the setup. After setup completed more commands will be available.');
        }
    }
}
