CREATE TABLE IF NOT EXISTS `%TABLE_PREFIX%article_slice` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `clang_id` int(11) NOT NULL,
    `ctype` int(11) NOT NULL,
    `priority` int(11) NOT NULL,
    `value1` text,
    `value2` text,
    `value3` text,
    `value4` text,
    `value5` text,
    `value6` text,
    `value7` text,
    `value8` text,
    `value9` text,
    `value10` text,
    `value11` text,
    `value12` text,
    `value13` text,
    `value14` text,
    `value15` text,
    `value16` text,
    `value17` text,
    `value18` text,
    `value19` text,
    `value20` text,
    `media1` varchar(255) DEFAULT NULL,
    `media2` varchar(255) DEFAULT NULL,
    `media3` varchar(255) DEFAULT NULL,
    `media4` varchar(255) DEFAULT NULL,
    `media5` varchar(255) DEFAULT NULL,
    `media6` varchar(255) DEFAULT NULL,
    `media7` varchar(255) DEFAULT NULL,
    `media8` varchar(255) DEFAULT NULL,
    `media9` varchar(255) DEFAULT NULL,
    `media10` varchar(255) DEFAULT NULL,
    `medialist1` text,
    `medialist2` text,
    `medialist3` text,
    `medialist4` text,
    `medialist5` text,
    `medialist6` text,
    `medialist7` text,
    `medialist8` text,
    `medialist9` text,
    `medialist10` text,
    `link1` varchar(10) DEFAULT NULL,
    `link2` varchar(10) DEFAULT NULL,
    `link3` varchar(10) DEFAULT NULL,
    `link4` varchar(10) DEFAULT NULL,
    `link5` varchar(10) DEFAULT NULL,
    `link6` varchar(10) DEFAULT NULL,
    `link7` varchar(10) DEFAULT NULL,
    `link8` varchar(10) DEFAULT NULL,
    `link9` varchar(10) DEFAULT NULL,
    `link10` varchar(10) DEFAULT NULL,
    `linklist1` text,
    `linklist2` text,
    `linklist3` text,
    `linklist4` text,
    `linklist5` text,
    `linklist6` text,
    `linklist7` text,
    `linklist8` text,
    `linklist9` text,
    `linklist10` text,
    `article_id` int(11) NOT NULL,
    `module_id` int(11) NOT NULL,
    `createdate` datetime NOT NULL,
    `updatedate` datetime NOT NULL,
    `createuser` varchar(255) NOT NULL,
    `updateuser` varchar(255) NOT NULL,
    `revision` int(11) NOT NULL,
    PRIMARY KEY (`id`),
    KEY `slice_priority` (`article_id`,`priority`,`module_id`),
    KEY `clang_id` (`clang_id`),
    KEY `article_id` (`article_id`),
    KEY `find_slices` (`clang_id`,`article_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;

CREATE TABLE IF NOT EXISTS `%TABLE_PREFIX%template` (
    `id` int(11) NOT NULL  auto_increment,
    `name` varchar(255) NULL,
    `content` text NULL,
    `active` tinyint(1) NULL,
    `createuser` varchar(255) NOT NULL,
    `updateuser` varchar(255) NOT NULL,
    `createdate` datetime NOT NULL,
    `updatedate` datetime NOT NULL,
    `attributes` text NULL,
    `revision` int(11) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;

CREATE TABLE IF NOT EXISTS `%TABLE_PREFIX%action` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `preview` text,
    `presave` text,
    `postsave` text,
    `previewmode` tinyint(4) DEFAULT NULL,
    `presavemode` tinyint(4) DEFAULT NULL,
    `postsavemode` tinyint(4) DEFAULT NULL,
    `createuser` varchar(255) NOT NULL,
    `createdate` datetime NOT NULL,
    `updateuser` varchar(255) NOT NULL,
    `updatedate` datetime NOT NULL,
    `revision` int(10) unsigned NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;

CREATE TABLE IF NOT EXISTS `%TABLE_PREFIX%module` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `output` text NOT NULL,
    `input` text NOT NULL,
    `createuser` varchar(255) NOT NULL,
    `updateuser` varchar(255) NOT NULL,
    `createdate` datetime NOT NULL,
    `updatedate` datetime NOT NULL,
    `attributes` text,
    `revision` int(10) unsigned NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;

CREATE TABLE IF NOT EXISTS `%TABLE_PREFIX%module_action` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `module_id` int(10) unsigned NOT NULL,
    `action_id` int(10) unsigned NOT NULL,
    `revision` int(10) unsigned NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;
