DROP TABLE IF EXISTS `%TABLE_PREFIX%article_slice`;

DROP TABLE IF EXISTS `%TABLE_PREFIX%template`;

DROP TABLE IF EXISTS `%TABLE_PREFIX%action`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%module`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%module_action`;
