package: phpmailer
version: '2.1.0-dev'
author: 'Markus Staab, Brent R. Matzelle'
supportpage: www.redaxo.org/de/forum/

page:
    title: PHPMailer
    perm: phpmailer[]
    pjax: true
    icon: rex-icon rex-icon-envelope
    subpages:
        config: { title: 'translate:configuration' }
        example: { title: 'translate:example' }

requires:
    redaxo: ^5.1.0-dev
