version: '5.0 alpha2'
author: 'Markus Staab, Brent R. Matzelle'
supportpage: www.redaxo.org/de/forum/

navigation:
  title: PHPMailer
  perm: phpmailer[]
  subpages:
    config: {title: 'translate:configuration'}
    example: {title: 'translate:example'}

requires:
  redaxo:
    min-version: '5.0.alpha3'
