package: phpmailer
version: '2.5.0-dev'
author: 'Markus Staab, Thomas Skerbis, Jan Kristinus, Brent R. Matzelle'
supportpage: www.redaxo.org/de/forum/

page:
    title: PHPMailer
    perm: phpmailer[]
    pjax: true
    icon: rex-icon rex-icon-envelope
    subpages:
        config: { title: 'translate:configuration' }
        help: { title: 'translate:help' }
        checkmail: { title: 'translate:checkmail', hidden: true}

pages:
    system/log/phpmailer:
        title: PHPMailer
        perm: admin

requires:
    redaxo: ^5.4.0
