package: phpmailer
version: '2.4.0'
author: 'Markus Staab, Brent R. Matzelle'
supportpage: www.redaxo.org/de/forum/

page:
    title: PHPMailer
    perm: phpmailer[]
    pjax: true
    icon: rex-icon rex-icon-envelope
    subpages:
        config: { title: 'translate:configuration' }
        help: { title: 'translate:help' }
        checkmail: { title: 'translate:checkmail', hidden: true}

requires:
    redaxo: ^5.1.0
