package: users
version: '2.5.0'
author: Jan Kristinus, Gregor Harlan
supportpage: www.redaxo.org/de/forum/

load: early

page:
    title: 'translate:users'
    perm: users[]
    block: system
    prio: 50
    pjax: true
    icon: rex-icon rex-icon-user
    subpages:
        users: { title: 'translate:users' }
        roles: { title: 'translate:roles', perm: admin }

requires:
    redaxo: ^5.5.0
