package: users
version: '2.8.0'
author: Jan Kristinus, Gregor Harlan
supportpage: https://github.com/redaxo/redaxo

load: early

page:
    title: 'translate:users'
    perm: users[]
    block: system
    prio: 50
    pjax: true
    icon: rex-icon rex-icon-user
    subpages:
        users: { title: 'translate:users' }
        roles: { title: 'translate:roles', perm: admin }

requires:
    php: '>=7.3'
    redaxo: ^5.12.0
