package: cronjob
version: '2.1.0'
author: 'Gregor Harlan'
supportpage: www.redaxo.org/de/forum/

page:
    title: 'translate:title'
    perm: admin[]
    pjax: true
    icon: rex-icon rex-icon-cronjob
    subpages:
        cronjobs: { title: 'translate:title' }
        log: { title: 'translate:log' }

requires:
    redaxo: ^5.1.0
