package: cronjob
version: '5.0 alpha2'
author: 'Gregor Harlan'
supportpage: www.redaxo.org/de/forum/

navigation:
  title: 'translate:title'
  perm: admin[]
  subpages:
    cronjobs: { title: 'translate:title' }
    log: { title: 'translate:log' }
