package: cronjob
version: '3.0.0-dev'
author: 'Gregor Harlan'
supportpage: https://github.com/redaxo/redaxo

page:
    title: 'translate:title'
    perm: admin[]
    pjax: true
    icon: rex-icon rex-icon-cronjob
    subpages:
        cronjobs: { title: 'translate:title' }
        log: { title: 'translate:log' }

pages:
    system/log/cronjob:
        title: Cronjob
        perm: admin[]

requires:
    php: '>=8.1'
    redaxo: ^6.0.0-dev
    packages:
        structure: '^3.0.0-dev'
        metainfo: '^3.0.0-dev'

console_commands:
    cronjob:run: rex_command_cronjob_run
