package: cronjob
version: '2.5.0-beta1'
author: 'Gregor Harlan'
supportpage: www.redaxo.org/de/forum/

page:
    title: 'translate:title'
    perm: admin[]
    pjax: true
    icon: rex-icon rex-icon-cronjob
    subpages:
        cronjobs: { title: 'translate:title' }
        log: { title: 'translate:log' }

pages:
    system/log/cronjob:
        title: Cronjob
        perm: admin[]

requires:
    redaxo: ^5.7

console_commands:
    cronjob:run: rex_command_cronjob_run
