package: cronjob
version: '2.8.0'
author: 'Gregor Harlan'
supportpage: https://github.com/redaxo/redaxo

page:
    title: 'translate:title'
    perm: admin[]
    pjax: true
    icon: rex-icon rex-icon-cronjob
    subpages:
        cronjobs: { title: 'translate:title' }
        log: { title: 'translate:log' }

pages:
    system/log/cronjob:
        title: Cronjob
        perm: admin[]

requires:
    php: '>=7.3'
    redaxo: ^5.9.0

console_commands:
    cronjob:run: rex_command_cronjob_run
