package: debug
version: '1.3.2'
author: Markus Staab, Marcel Kuhmann, Gregor Harlan
supportpage: https://github.com/redaxo/redaxo

load: early

page:
    title: translate:debug
    perm: admin
    live_mode: false
    block: system
    pjax: false
    icon: rex-icon rex-icon-heartbeat
    linkAttr: { target: _blank }

requires:
    php:
        version: '>=8.1'
        extensions: [zip]
    redaxo: ^5.13.0
