package: debug
version: '0.1.0-dev'
author: Markus Staab, Marcel Kuhmann
supportpage: redaxo.org

load: early

page:
    title: translate:debug
    perm: admin
    block: system
    pjax: false
    icon: rex-icon rex-icon-heartbeat
    linkAttr: { target: _blank }

requires:
    redaxo: ^5.11-dev
