package: debug
version: '1.1.0-dev'
author: Markus Staab, Marcel Kuhmann, Gregor Harlan
supportpage: https://github.com/redaxo/redaxo

load: early

page:
    title: translate:debug
    perm: admin
    block: system
    pjax: false
    icon: rex-icon rex-icon-heartbeat
    linkAttr: { target: _blank }

requires:
    php: '>=7.3'
    redaxo: ^5.11.0
