package: mediapool
version: '2.16.0'
author: 'Jan Kristinus'
supportpage: https://github.com/redaxo/redaxo

rows_per_page: 100

page:
    title: translate:mediapool
    popup: openMediaPool(); return false;
    perm: media/hasMediaPerm
    prio: 20
    block: system
    pjax: true
    icon: rex-icon rex-icon-media
    subpages:
        media:     { title: translate:pool_file_list }
        upload:    { title: translate:pool_file_insert }
        structure: { title: translate:pool_cat_list,   perm: media/hasAll }
        sync:      { title: translate:pool_sync_files, perm: media[sync] }

blocked_extensions: [asp, aspx, bat, cfm, cgi, flv, hh, html, htaccess, htpasswd, ini, jsp, jsf, js, jsphp, log, mjs, pht, php, php3, php4, php5, php6, php7, php8, phar, pl, ps1, phtml, py, rb, rm, sh, shmtl, shtml, swf, wasm, wmv, wma, xhtml, xht, xml]

# mime type allowlist. the list is checked after the blocked_extensions check from above has passed.
allowed_mime_types:
    avif: [image/avif]
    gif: [image/gif]
    jpg: [image/jpeg, image/pjpeg]
    jpeg: [image/jpeg, image/pjpeg]
    png: [image/png]
    webp: [image/webp]
    eps: [application/postscript]
    tif: [image/tiff]
    tiff: [image/tiff]
    svg: [image/svg+xml]
    pdf: [application/pdf]
    xls: [application/vnd.ms-excel, application/octet-stream, application/encrypted]
    xlsx: [application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/octet-stream, application/encrypted]
    doc: [application/msword, application/octet-stream, application/encrypted]
    docx: [application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/octet-stream, application/encrypted]
    dot: [application/msword, application/octet-stream, application/encrypted]
    dotx: [application/vnd.openxmlformats-officedocument.wordprocessingml.template, application/octet-stream, application/encrypted]
    ppt: [application/vnd.ms-powerpoint]
    pptx: [application/vnd.openxmlformats-officedocument.presentationml.presentation]
    pot: [application/vnd.ms-powerpoint]
    potx: [application/vnd.openxmlformats-officedocument.presentationml.template]
    pps: [application/vnd.ms-powerpoint]
    ppsx: [application/vnd.openxmlformats-officedocument.presentationml.slideshow]
    rtf: [application/rtf]
    txt: [text/plain, application/octet-stream]
    csv: [text/plain, text/csv, application/octet-stream]
    zip: [application/x-zip-compressed, application/zip]
    gz: [application/x-gzip]
    tar: [application/x-tar]
    mov: [video/quicktime]
    movie: [video/quicktime]
    mp3: [audio/mpeg]
    mpe: [video/mpeg]
    mpeg: [video/mpeg]
    mpg: [video/mpeg]
    mp4: [video/mp4]

allowed_doctypes: [avif, bmp, css, csv, doc, docx, eps, gif, gz, jpg, jpeg, mov, mp3, mp4, ogg, pdf, png, ppt, pptx, pps, ppsx, rar, rtf, svg, swf, tar, tif, tiff, txt, webp, wma, xls, xlsx, zip]
image_extensions: [avif, bmp, gif, jpeg, jpg, png, svg, tif, tiff, webp]
sanitize_svgs: true

requires:
    php: '>=8.1'
    redaxo: ^5.18.2
