package: mediapool
version: '2.12.0'
author: 'Jan Kristinus'
supportpage: https://github.com/redaxo/redaxo

page:
    title: translate:mediapool
    popup: openMediaPool(); return false;
    perm: media/hasMediaPerm
    prio: 20
    block: system
    pjax: true
    icon: rex-icon rex-icon-media
    subpages:
        media:     { title: translate:pool_file_list }
        upload:    { title: translate:pool_file_insert }
        structure: { title: translate:pool_cat_list,   perm: media/hasAll }
        sync:      { title: translate:pool_sync_files, perm: media[sync] }

blocked_extensions: [php, php3, php4, php5, php6, php7, php8, phar, pht, phtml, hh, pl, asp, aspx, cfm, jsp, jsf, bat, sh, cgi, htaccess, htpasswd]

# optional mime type allowlist. the list is checked after the blocked_extensions check from above has passed.
# exmaple:
#   allowed_mime_types:
#       gif: [image/gif]
#       jpg: [image/jpeg, image/pjpeg]
allowed_mime_types: ~

allowed_doctypes: [bmp, css, doc, docx, eps, gif, gz, jpg, jpeg, mov, mp3, mp4, ogg, pdf, png, ppt, pptx, pps, ppsx, rar, rtf, svg, swf, tar, tif, tiff, txt, webp, wma, xls, xlsx, zip]
image_extensions: [bmp, gif, jpeg, jpg, png, svg, tif, tiff, webp]

requires:
    php: '>=7.3'
    redaxo: ^5.13.0
