package: mediapool
version: '5.0-alpha7'
author: 'Jan Kristinus'
supportpage: www.redaxo.org/de/forum/

page:
    title: translate:mediapool
    popup: openMediaPool(); return false;
    perm: media/hasMediaPerm
    prio: 20
    block: system
    subpages:
        media:     { title: translate:pool_file_list }
        upload:    { title: translate:pool_file_insert }
        structure: { title: translate:pool_cat_list,   perm: media/hasAll }
        sync:      { title: translate:pool_sync_files, perm: media/hasAll }

blocked_extensions: [php, php3, php4, php5, php6, phtml, pl, asp, aspx, cfm, jsp, jsf, bat, sh, cgi]
allowed_doctypes: [bmp, css, doc, docx, eps, gif, gz, jpg, mov, mp3, ogg, pdf, png, ppt, pptx, pps, ppsx, rar, rtf, swf, tar, tif, txt, wma, xls, xlsx, zip]
image_extensions: [gif, jpeg, jpg, png, bmp]
image_types: [image/gif, image/jpg, image/jpeg, image/png, image/x-png, image/pjpeg, image/bmp]
