name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Willkommen bei REDAXO. Wir freuen uns über dein 1. Issue 🥰.'
        pr-message: 'Servus! Danke für deine erste Mithilfe an REDAXO 😘. Bitte hab etwas Geduld, wir versuchen Dir baldmöglichst Feedback zu geben.'
