name: PHP Checks

on:
    push:
        branches:
            - master
            - bugfix
            - temp
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches:
            - '*'

jobs:

    phpunit:
        name: mariadb unit tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
              mariadb-versions: ['10.1', 'latest']   
        if: "!contains(github.event.head_commit.message, '[ci skip]')"

# https://docs.github.com/en/free-pro-team@latest/actions/guides/about-service-containers
        services:
            mysql:
                # a docker-hub key https://hub.docker.com/_/mariadb?tab=tags
                image: mariadb:${{ matrix.mariadb-versions }}
                ports:
                    - 3306
                env:
                    MYSQL_USER: root
                    MYSQL_PASSWORD: root
                    MYSQL_DATABASE: redaxo5
                    MYSQL_ROOT_PASSWORD: root
        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  extensions: intl
                  coverage: none # disable xdebug, pcov
            - uses: "ramsey/composer-install@v1"
              with:
                  composer-options: "--ansi --prefer-dist"

            - name: Setup Problem Matchers for PHPUnit
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - run: |
                  sudo /etc/init.d/mysql start
                  mysql -uroot -h127.0.0.1 -proot -e 'create database redaxo5;'
                  git apply .github/workflows/default.config.yml.github-action.diff
            - run: |
                  php .tools/bin/setup
            - run: |
                  vendor/bin/phpunit --colors=always
