name: PHP Checks

on:
    push:
        branches:
            - master
            - bugfix
            - temp
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches:
            - '*'

jobs:

    phpunit:
        name: mysql unit tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
              php-versions: ['7.3', '7.4', '8.0']    
        if: "!contains(github.event.head_commit.message, '[ci skip]')"

        services:
            mysql:
                image: mysql:5.7
                ports:
                    - 3306
        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: intl
                  coverage: none # disable xdebug, pcov

            - name: "composer install --prefer-dist"
              uses: "ramsey/composer-install@v1"
              if: matrix.php-versions != '8.0'
              with:
                  composer-options: "--ansi --prefer-dist"
            - name: "composer install --prefer-dist --ignore-platform-reqs"
              uses: "ramsey/composer-install@v1"
              if: matrix.php-versions == '8.0'
              with:
                  composer-options: "--ansi --prefer-dist --ignore-platform-reqs"

            - name: Setup Problem Matchers for PHPUnit
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - run: |
                  sudo /etc/init.d/mysql start
                  mysql -uroot -h127.0.0.1 -proot -e 'create database redaxo5;'
                  git apply .github/workflows/default.config.yml.github-action.diff
            - run: |
                  php .tools/bin/setup
            - run: |
                  vendor/bin/phpunit --colors=always
