name: Remove automerge label

on:
    pull_request_target:
        types: [closed]

permissions:
  contents: read

jobs:
    remove-automerge-label:
        permissions:
          contents: none
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true

        steps:
            -   uses: actions-ecosystem/action-remove-labels@v1
                with:
                    github_token: ${{ secrets.BOT_TOKEN }}
                    labels: automerge
