package: metainfo
version: '2.11.0'
author: 'Markus Staab, Jan Kristinus'
supportpage: https://github.com/redaxo/redaxo

page:
    title: Meta Infos
    perm: admin[]
    live_mode: false
    pjax: true
    icon: rex-icon rex-icon-metainfo
    subpages:
        articles: { title: 'translate:articles' }
        categories: { title: 'translate:categories' }
        media: { title: 'translate:media' }
        clangs: { title: 'translate:clangs' }

requires:
    php: '>=8.1'
    redaxo: ^5.17.0
    packages:
        structure: '^2.12.1'
        mediapool: '^2.10.1'
