package: metainfo
version: '2.7.3'
author: 'Markus Staab, Jan Kristinus'
supportpage: https://github.com/redaxo/redaxo

page:
    title: Meta Infos
    perm: admin[]
    pjax: true
    icon: rex-icon rex-icon-metainfo
    subpages:
        articles: { title: 'translate:articles' }
        categories: { title: 'translate:categories' }
        media: { title: 'translate:media' }
        clangs: { title: 'translate:clangs' }

requires:
    php: '>=7.1'
    redaxo: '^5.6.0'
    packages:
        structure: '^2.0.0'
        mediapool: '^2.0.0'
