package: metainfo
version: '2.3.1'
author: 'Markus Staab, Jan Kristinus'
supportpage: www.redaxo.org/de/forum/

page:
    title: Meta Infos
    perm: admin[]
    pjax: true
    icon: rex-icon rex-icon-metainfo
    subpages:
        articles: { title: 'translate:articles' }
        categories: { title: 'translate:categories' }
        media: { title: 'translate:media' }
        clangs: { title: 'translate:clangs' }
pages:
    content/metainfo: { title: 'translate:metadata', icon: rex-icon rex-icon-metainfo }

requires:
    redaxo: '^5.5.0'
    packages:
        structure: '^2.0.0'
        mediapool: '^2.0.0'
