package: metainfo
version: '5.0 a1'
author: 'Markus Staab, Jan Kristinus'
supportpage: www.redaxo.org/de/forum/

navigation:
  title: Meta Infos
  perm: admin[]
  subpages:
    articles: { title: 'translate:articles' }
    categories: { title: 'translate:categories' }
    media: { title: 'translate:media' }

requires:
  packages:
    structure: '~ 5.0 alpha'
    mediapool: '~ 5.0 alpha'
